#!/usr/bin/env python3
"""Makes the game-event table for our code out of the server's binary.

    tools/linuxded/gen_events.py > src/net/src/bf2_events.inc

For every event it takes the type number from `getType()` and the field layout
from `deSerialize`. Events whose fields sit behind a condition are marked
separately: for them a size table would lie, so the parsing of those is written
by hand, and the generator says so honestly instead of emitting wrong code.

The point of the table is being able to skip any event by exactly as many bits as
it occupies. Without that the end of a packet cannot be reached, and the ghost
stream is waiting there.
"""
import re
import subprocess
import sys

import bitfields as b


def event_types(table):
    """Every event's type number from its `getType()`."""
    wanted = {}
    for name, (address, size) in table.items():
        head = name.split("(")[0]
        if head.endswith("::getType"):
            wanted[head] = (address, size or 0x20)

    numbers = {}
    for head, (address, size) in wanted.items():
        cls = head.split("::")[-2]
        text = subprocess.run(
            ["objdump", "-d", "--no-show-raw-insn",
             "--start-address=0x%x" % address,
             "--stop-address=0x%x" % (address + max(size, 0x10)), b.BINARY],
            capture_output=True, text=True).stdout
        m = re.search(r"movl?\s+\$0x([0-9a-f]+),\s*%eax", text)
        if m:
            value = int(m.group(1), 16)
        elif re.search(r"xorl?\s+%eax,\s*%eax", text):
            value = 0
        else:
            continue
        if value < 128:
            numbers.setdefault(cls, value)
    return numbers


def layout(table, cls):
    """(field sizes, whether there are conditional branches) for `<cls>::deSerialize`."""
    hit = b.find(table, "%s::deSerialize" % cls)
    if not hit:
        return None, False
    address, size, _ = hit
    lines = b.disassemble(address, size)
    steps = b.scan(lines)
    fields = [s for s in steps if s[0] in ("field", "string")]
    if not fields:
        return [], False
    first, last = fields[0][1], fields[-1][1]
    branchy = any(s[0] == "branch" and first <= s[1] <= last for s in steps)
    widths = [v if k == "field" else None for k, _, v in fields]
    return widths, branchy


def main():
    table = b.symbols()
    numbers = event_types(table)

    rows = []
    for cls, number in sorted(numbers.items(), key=lambda kv: kv[1]):
        if not cls.endswith("Event"):
            continue
        widths, branchy = layout(table, cls)
        if widths is None:
            continue
        rows.append((number, cls, widths, branchy))

    print("// Generated by tools/linuxded/gen_events.py from bin/amd-64/bf2.")
    print("// Do not edit by hand: it can be re-taken with the same command.")
    print("//")
    print("// BF2_EVENT(number, name, bits...) — the fields run consecutively, so")
    print("// such an event can be skipped by the table.")
    print("// BF2_EVENT_BRANCHY(number, name) — some fields are conditional, the")
    print("// size depends on the contents, so the parsing is written by hand.")
    print("// BF2_EVENT_EMPTY(number, name) — an event with no fields, the type alone.")
    print()
    for number, cls, widths, branchy in rows:
        if branchy or any(w is None for w in widths):
            print("BF2_EVENT_BRANCHY(%d, \"%s\")" % (number, cls))
        elif not widths:
            print("BF2_EVENT_EMPTY(%d, \"%s\")" % (number, cls))
        else:
            print("BF2_EVENT(%d, \"%s\"%s)" % (
                number, cls, "".join(", %d" % w for w in widths)))
    print()
    print("// events in all: %d, of them conditional: %d"
          % (len(rows), sum(1 for r in rows if r[3])), file=sys.stderr)


if __name__ == "__main__":
    main()
